version: "3.8"

services:
  api:
    build: ./services/api
    command:
      - /bin/bash
      - -c
      - |
        poetry run python manage.py migrate
        poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./services/api/:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=kalvisquad
      - DATABASE_NAME=kalvi
      - DATABASE_USER=kalvi
      - DATABASE_PASSWORD=kalvi
      - DATABASE_HOST=db
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_HOST_USER=USER
      - EMAIL_HOST_PASSWORD=PASSWORD
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - GOOGLE_CLIENT_ID=client_Id
      - GITHUB_CLIENT_ID=client_id
      - GITHUB_SECRET=secret
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=kalvi
      - POSTGRES_PASSWORD=kalvi
      - POSTGRES_DB=kalvi
  redis:
    image: redis:alpine
volumes:
  postgres_data:
